name: Build(RISC-V)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t duckdb-riscv-ci -f Dockerfile .
      
      - name: Tag Docker Image
        run: docker tag duckdb-riscv-ci ghcr.io/mocusez/duckdb-riscv-ci/duckdb-riscv-ci:latest
      
      - name: Push Docker Image
        run: docker push ghcr.io/mocusez/duckdb-riscv-ci/duckdb-riscv-ci:latest

      
      
