name: Build(RISC-V)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependent and start environment
        run: |
          sudo apt-get install -y qemu-system u-boot-qemu openssh-server screen sshpass
          qemu-system-riscv64 \
            -machine virt \
            -cpu rv64,zba=true,zbb=true,v=true,vlen=256,vext_spec=v1.0,rvv_ta_all_1s=true,rvv_ma_all_1s=true \
            -smp 4 \
            -m 4G \
            -device virtio-blk-device,drive=hd \
            -drive file=image.qcow2,if=none,id=hd \
            -device virtio-net-device,netdev=net \
            -netdev user,id=net,hostfwd=tcp::2222-:22 \
            -kernel /usr/lib/u-boot/qemu-riscv64_smode/uboot.elf \
            -append "root=LABEL=rootfs console=ttyS0" \
            -nographic

      - name: Wait for qemu to start
        run: sleep 60

      - name: Build RISC-V Version DuckDB
        run: |
          sshpass -p 'root' ssh -p 2222 root@localhost "apt-get update && apt-get install -y git g++ cmake ninja-build libssl-dev"
          sshpass -p 'root' ssh -p 2222 root@localhost "git clone https://github.com/duckdb/duckdb.git"
          sshpass -p 'root' ssh -p 2222 root@localhost "cd duckdb && CORE_EXTENSIONS='tpch' GEN=ninja CC='gcc -march=rv64gcv_zicsr_zifencei_zihintpause_zvl256b' CXX='g++ -march=rv64gcv_zicsr_zifencei_zihintpause_zvl256b'  make"
      
